package com.qbthon.model;

import java.util.Date;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "event_details")
public class EventDetails {
	
	private String eventId;
	
	private String eventName;
	
	private Date eventDate;
	
	private String eventSlot;
	
	private String eventstartTime;
	
	private String eventEndTime;
	
	private Set<String> eventSkills;
	
	private Set<String> associateList;
	
	private Set<String> smeList;
	
	private Integer totalNoOfSkillsCovered;
	
	private Integer totalNoOfMCQs;
	
	private Set<String> voucherWinners;
	
	public EventDetails() {
		super();
	}

	
	public EventDetails(String eventId, String eventName, Date eventDate, String eventSlot, String eventstartTime,
			String eventEndTime, Set<String> eventSkills, Set<String> associateList, Set<String> smeList,
			Integer totalNoOfSkillsCovered, Integer totalNoOfMCQs, Set<String> voucherWinners) {
		super();
		this.eventId = eventId;
		this.eventName = eventName;
		this.eventDate = eventDate;
		this.eventSlot = eventSlot;
		this.eventstartTime = eventstartTime;
		this.eventEndTime = eventEndTime;
		this.eventSkills = eventSkills;
		this.associateList = associateList;
		this.smeList = smeList;
		this.totalNoOfSkillsCovered = totalNoOfSkillsCovered;
		this.totalNoOfMCQs = totalNoOfMCQs;
		this.voucherWinners = voucherWinners;
	}
	@DynamoDBHashKey(attributeName = "event_id")
	@DynamoDBAutoGeneratedKey
	public String getEventId() {
		return eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	@DynamoDBAttribute(attributeName = "eventName")
	public String getEventName() {
		return eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@DynamoDBAttribute(attributeName = "eventDate")
	public Date getEventDate() {
		return eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	@DynamoDBAttribute(attributeName = "eventSlot")
	public String getEventSlot() {
		return eventSlot;
	}

	public void setEventSlot(String eventSlot) {
		this.eventSlot = eventSlot;
	}

	@DynamoDBAttribute(attributeName = "eventSkills")
	public Set<String> getEventSkills() {
		return eventSkills;
	}

	public void setEventSkills(Set<String> eventSkills) {
		this.eventSkills = eventSkills;
	}

	@DynamoDBAttribute(attributeName = "associateList")
	public Set<String> getAssociateList() {
		return associateList;
	}

	public void setAssociateList(Set<String> associateList) {
		this.associateList = associateList;
	}

	@DynamoDBAttribute(attributeName = "smeList")
	public Set<String> getSmeList() {
		return smeList;
	}

	public void setSmeList(Set<String> smeList) {
		this.smeList = smeList;
	}

	@DynamoDBAttribute(attributeName = "totalNoOfSkillsCovered")
	public Integer getTotalNoOfSkillsCovered() {
		return totalNoOfSkillsCovered;
	}

	public void setTotalNoOfSkillsCovered(Integer totalNoOfSkillsCovered) {
		this.totalNoOfSkillsCovered = totalNoOfSkillsCovered;
	}

	@DynamoDBAttribute(attributeName = "totalNoOfMCQs")
	public Integer getTotalNoOfMCQs() {
		return totalNoOfMCQs;
	}

	public void setTotalNoOfMCQs(Integer totalNoOfMCQs) {
		this.totalNoOfMCQs = totalNoOfMCQs;
	}

	@DynamoDBAttribute(attributeName = "voucherWinners")
	public Set<String> getVoucherWinners() {
		return voucherWinners;
	}

	public void setVoucherWinners(Set<String> voucherWinners) {
		this.voucherWinners = voucherWinners;
	}

	@DynamoDBAttribute(attributeName = "eventstartTime")
	public String getEventstartTime() {
		return eventstartTime;
	}


	public void setEventstartTime(String eventstartTime) {
		this.eventstartTime = eventstartTime;
	}

	@DynamoDBAttribute(attributeName = "eventEndTime")
	public String getEventEndTime() {
		return eventEndTime;
	}


	public void setEventEndTime(String eventEndTime) {
		this.eventEndTime = eventEndTime;
	}


	@Override
	public String toString() {
		return "EventDetails [eventId=" + eventId + ", eventName=" + eventName + ", eventDate=" + eventDate
				+ ", eventSlot=" + eventSlot + ", eventstartTime=" + eventstartTime + ", eventEndTime=" + eventEndTime
				+ ", eventSkills=" + eventSkills + ", associateList=" + associateList + ", smeList=" + smeList
				+ ", totalNoOfSkillsCovered=" + totalNoOfSkillsCovered + ", totalNoOfMCQs=" + totalNoOfMCQs
				+ ", voucherWinners=" + voucherWinners + "]";
	}

}
